### ISSUE TITLE
Mouse pointer should become an arrow when hovering over Login button

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#130]
A fairly small thing, but worth getting right.

**Comment by mtaghiza** [comment]
Hi Jordan, do you guys have the code for this in some other branch? I'll incorporate it in sciserver_vm.

**Comment by raddick** [comment]
I'm testing this on scitest02/skyserver , so it should be v1_5_1 on the 
sciserver_vm branch, right?

Oh, wait, maybe this is in the portal instead. Which branch is driving

http://scitest02.pha.jhu.edu/login-portal/

?

~Jordan

**Comment by bonbons0220** [comment]
The mouse pointer should be a pointer when hovering over any button (pointer is a pointing finger), not an arrow. This is standard. Add this to the element:

 onmouseover="this.style.cursor='pointer'"

**Comment by mtaghiza** [comment]
Fixed. Pointer will appear on mouse-over in the version right after sciserver-v1.5.1

**Comment by raddick** [comment]
^---- What @bonbons0220  said about how I should have asked for a pointer instead of an arrow.

@mtaghiza , thanks for the super-quick fix!

I'm pretty sure the next version will be sciserver_v1_6_0 (major-releasing because we'll be adding CasJobs account migration), so I've created a milestone named that.

**Comment by raddick** [comment]
Changed milestone to v1_5_2 , since that would be the next version after the current test version.

**Comment by raddick** [comment]
Still appears in sciserver_v1_5_1 , but I think the plan was to create this fix for the next release and test it in sciserver_v1_6_0 . So removing the needstest label for now, to be put back when we release sciserver_v1_6_0 .

**Comment by raddick** [comment]
Realized that I should leave the needstest label in place. When combined with the sciserver_v1_6_0 milestone, needstest is needed to identify something as we should test in that release (even though we're not testing it for the sciserver_v1_5_1 release). Restoring it.

**Comment by mtaghiza** [comment]
Tested and confirmed the fix, as of sciserver-v1.8.1. Closing...
